# Use postgres/example user/password credentials

services:

  db:
    image: postgres
    container_name: reservation-service-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: popcorn
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - reservation-service-db-data:/var/lib/postgresql
    networks:
      - internal

  adminer:
    image: adminer
    container_name: reservation-service-adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - internal
  
  reservation-service:
    build: ./reservation-service
    container_name: reservation-service
    restart: always
    ports:
      - 4000:4000
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: popcorn
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    depends_on:
      - db
    networks:
      - internal

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    restart: always
    environment:
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - CLUSTER_ID=5L6g3nShT-eMCtK--X86sw
    ports:
      - 9092:9092
      - 9094:9094
    networks:
      - internal

volumes:
  reservation-service-db-data:

networks:
  internal:
    driver: bridge